"""NIFTY 50 stock tickers configuration"""

# Primary: NSE (.NS), Fallback: BSE (.BO)
NIFTY_50_TICKERS = [
    "RELIANCE.NS",
    "TCS.NS",
    "HDFCBANK.NS",
    "INFY.NS",
    "ICICIBANK.NS",
    "HINDUNILVR.NS",
    "ITC.NS",
    "SBIN.NS",
    "BHARTIARTL.NS",
    "KOTAKBANK.NS",
    "LT.NS",
    "AXISBANK.NS",
    "BAJFINANCE.NS",
    "ASIANPAINT.NS",
    "MARUTI.NS",
    "HCLTECH.NS",
    "WIPRO.NS",
    "TITAN.NS",
    "ULTRACEMCO.NS",
    "NESTLEIND.NS",
    "SUNPHARMA.NS",
    "TATAMOTORS.NS",
    "BAJAJFINSV.NS",
    "TECHM.NS",
    "POWERGRID.NS",
    "ONGC.NS",
    "NTPC.NS",
    "M&M.NS",
    "TATASTEEL.NS",
    "ADANIENT.NS",
    "ADANIPORTS.NS",
    "COALINDIA.NS",
    "DIVISLAB.NS",
    "DRREDDY.NS",
    "EICHERMOT.NS",
    "GRASIM.NS",
    "HDFCLIFE.NS",
    "HEROMOTOCO.NS",
    "HINDALCO.NS",
    "INDUSINDBK.NS",
    "JSWSTEEL.NS",
    "BRITANNIA.NS",
    "CIPLA.NS",
    "APOLLOHOSP.NS",
    "BPCL.NS",
    "SBILIFE.NS",
    "TRENT.NS",
    "BAJAJ-AUTO.NS",
    "SHRIRAMFIN.NS",
    "LTIM.NS"
]

def get_nifty50_tickers():
    """Returns list of NIFTY 50 stock symbols"""
    return NIFTY_50_TICKERS